In [14]:
import numpy as np
a = np.array([1,9,3])
b = np.array([8,4,5])
print("arrays")
print(a)
print(b)
print("greater is")
print(np.greater(a,b))
print("lesser is")
print(np.less(a,b))
print("greater or equal")
print(np.greater_equal(a,b))
print("lesser or equal")
print(np.less_equal(a,b))

arrays
[1 9 3]
[8 4 5]
greater is
[False  True False]
lesser is
[ True False  True]
greater or equal
[False  True False]
lesser or equal
[ True False  True]


In [46]:
import numpy as np
a=np.arange(30,71,2)
print("even numbers from 30 to 70 are:")
print(a)

even numbers from 30 to 70 are:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [15]:
import numpy as np
a=np.identity(3)
print("3*3 matrix is")
print(a)

3*3 matrix is
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
import numpy as np
x=np.arange(21)
print("vector is")
print(x)
x[(x>=9)&(x<=15)]*=-1
print("vector after changing the signs")
print(x)




vector is
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
vector after changing the signs
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [19]:
import numpy as np
x=np.diag([1,2,3,4,5])
print("5*5 matrix is")
print(x)

5*5 matrix is
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [27]:
import numpy as np
a=np.array([[4,5],[7,6]])
print("arrays ")
print(a)
print("sum of elements ")
print(np.sum(a))
print("sum of each row")
print(np.sum(a,axis=1))
print("sum of each column")
print(np.sum(a,axis=0))



arrays 
[[4 5]
 [7 6]]
sum of elements 
22
sum of each row
[ 9 13]
sum of each column
[11 11]


In [37]:
import numpy as np
import os
a=np.arange(6).reshape(3,2)
print(a)
header = 'col1 col2 col3'
np.savetxt('t.txt', a, fmt="%d", header=header) 
print("After loading, content of the text file:")
r = np.loadtxt('t.txt')
print(r)

[[0 1]
 [2 3]
 [4 5]]
After loading, content of the text file:
[[0. 1.]
 [2. 3.]
 [4. 5.]]


In [40]:
import numpy as np
a = np.array([1,2,3])
b = np.array([1,2,3])
print("arrays are")
print(a,b)
print("after testing")
eq=np.allclose(a,b)
print(eq)

arrays are
[1 2 3] [1 2 3]
after testing
True


In [42]:
import numpy as np
n=np.arange(16).reshape(4,4)
print("array")
print(n)
print("after swapping")
n[[0,-1],:]=n[[-1,0],:]
print(n)


array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
after swapping
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [43]:
import numpy as np
a = np.array([1,2,3])
b = np.array([8,7,6])
print("arrays")
print(a,b)
print("after multipication")
print(np.multiply(a,b))


arrays
[1 2 3] [8 7 6]
after multipication
[ 8 14 18]
